logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
    org.springframework.web: ERROR

server.port: 8019

spring:
  datasource.url: jdbc:postgresql://127.0.0.1:5434/oloola
  datasource.driverClassName: org.postgresql.Driver
  security.basic.enable: false
  management.security.enabled: false
  datasource.username: oloola
  datasource.password:
  jpa.database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  jpa.show-sql: true
  jpa.properties.hibernate.use_sql_comments: true
  jpa.hibernate.ddl-auto: create
  h2.console.enabled: true
  h2.console.path: /h2
