logging:
  level:
    org:
      springframework: DEBUG
      security: DEBUG
    org.springframework.web: ERROR

server.port: 8019

spring:
  datasource.url: jdbc:h2:mem:oloola
  datasource.driverClassName: org.h2.Driver
  security.basic.enable: false
  management.security.enabled: false
  datasource.username: sa
  datasource.password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa.show-sql: true
  h2.console.enabled: true
  h2.console.path: /h2
