logging:
  level:
    org:
      springframework:
    org.springframework.web: ERROR

server.port: 8019

spring:
  datasource.url: jdbc:postgresql://localhost:5432/oloola
  datasource.driverClassName: org.postgresql.Driver
  security.basic.enable: false
  management.security.enabled: false
  datasource.username: oloola
  datasource.password: oloola
  jpa.database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  jpa.show-sql: true
  jpa.properties.hibernate.use_sql_comments: true
  jpa.hibernate.ddl-auto: update
  h2.console.enabled: true
  h2.console.path: /h2
  servlet.multipart.enabled: true
  servlet.multipart.file-size-threshold: 2KB
  servlet.multipart.max-file-size: 200MB
  servlet.multipart.max-request-size: 215MB
file.upload-dir: $HOME/uploads