logging:
  level:
    org:
    springframework:
    security: DEBUG
    org.springframework.web: ERROR

server.port: 8082

spring:
  datasource.url: jdbc:h2:mem:savings
  datasource.driverClassName: org.h2.Driver
  datasource.username: sa
  datasource.password:
  jpa.database-platform: org.hibernate.dialect.H2Dialect

